CREATE TABLE DOCTOR
(
    NAME VARCHAR2(20),
    SPACIALIZATION VARCHAR2(2),
    FEE NUMBER,
    CONSTRAINT DOCTOR_PK PRIMARY KEY (NAME, SPACIALIZATION)
);

CREATE TABLE PATIENT
(
    PATIENT_NO VARCHAR2(5),
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(10),
    CONSTRAINT PATIENT_PK PRIMARY KEY (PATIENT_NO)
);

CREATE TABLE APPOINTMENT
(
    PATIENT_NO VARCHAR2(5),
    NAME VARCHAR2(20),
    SPACIALIZATION VARCHAR2(2),
    CONSTRAINT APPOINTMENT_PK PRIMARY KEY (PATIENT_NO, NAME, SPACIALIZATION)
);
