-- CIP

SELECT COUNT(*) AS Account_Count FROM ( SELECT A_ID, SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END) AS Total_Balance, SUM(AMOUNT) AS Total_Amount_of_Transactions FROM TRANSACTIONS GROUP BY A_ID HAVING SUM(AMOUNT) >= 5000000 AND (SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END)) >= 1000000) AccountsWithCriteria;


-- VIP
SELECT COUNT(*) AS Account_Count FROM ( SELECT A_ID, SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END) AS Total_Balance, SUM(AMOUNT) AS Total_Amount_of_Transactions FROM TRANSACTIONS GROUP BY A_ID HAVING  (SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END) >= 500000 AND (SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END) <= 900000) AND SUM(AMOUNT) >= 2500000 AND SUM(AMOUNT) <= 4500000 )) AccountsWithCriteria;

--OP
SELECT COUNT(*) AS Account_Count FROM ( SELECT A_ID, SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END) AS Total_Balance, SUM(AMOUNT) AS Total_Amount_of_Transactions FROM TRANSACTIONS GROUP BY A_ID HAVING SUM(AMOUNT) <= 1000000 AND (SUM(CASE WHEN TYPE = '0' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = '1' THEN AMOUNT ELSE 0 END)) <= 1000000 ) AccountsWithCriteria;